# -*- coding: utf-8 -*-
"""currencyconvertor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qAgJtH9tPQpCSkyYazxHxopBmy55aa1Q
"""

pip install requests pandas

import requests

def get_exchange_rates(base_currency="USD"):
    url = f"https://api.exchangerate-api.com/v4/latest/{base_currency}"
    response = requests.get(url)
    data = response.json()
    return data["rates"]

def convert_currency(amount, from_currency, to_currency, rates):
    if from_currency not in rates or to_currency not in rates:
        return "Invalid Currency Code"
    converted_amount = amount * (rates[to_currency] / rates[from_currency])
    return round(converted_amount, 2)

# Example Usage
rates = get_exchange_rates()
amount = float(input("Enter amount: "))
from_currency = input("From Currency (e.g., USD): ").upper()
to_currency = input("To Currency (e.g., INR): ").upper()

result = convert_currency(amount, from_currency, to_currency, rates)
print(f"{amount} {from_currency} = {result} {to_currency}")

import requests

# Replace 'YOUR_API_KEY' with your actual key
API_KEY = "46a14ebb1cb231e7174576c6"
BASE_URL = f"https://v6.exchangerate-api.com/v6/{API_KEY}/latest/"

def get_exchange_rates(base_currency="USD"):
    url = BASE_URL + base_currency
    response = requests.get(url)
    data = response.json()

    if data["result"] == "success":
        return data["conversion_rates"]
    else:
        return None  # Handle error

def convert_currency(amount, from_currency, to_currency, rates):
    if from_currency not in rates or to_currency not in rates:
        return "Invalid Currency Code"
    converted_amount = amount * (rates[to_currency] / rates[from_currency])
    return round(converted_amount, 2)

# Example Usage
rates = get_exchange_rates()
if rates:
    amount = float(input("Enter amount: "))
    from_currency = input("From Currency (e.g., USD): ").upper()
    to_currency = input("To Currency (e.g., INR): ").upper()

    result = convert_currency(amount, from_currency, to_currency, rates)
    print(f"{amount} {from_currency} = {result} {to_currency}")
else:
    print("Error fetching exchange rates. Check your API key.")



